version: '3.8'

services:
  mydb:
    image: stackupiss/northwind-db:v1
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
     - northwind-net
    volumes:
      - ./mydb_data:/var/lib/mysql

  myapp:
    image: stackupiss/northwind-app:v1
    container_name: myapp
    environment:
      DB_HOST: mydb
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "8080:3000"
    networks:
      - northwind-net
    depends_on:
      - mydb

networks:
  northwind-net:
    driver: bridge