---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAIyGEgto1OYnr7/rl1d9i8fLWw8iBixHMCrOS1MJKgQ0SLKXkwwOfOVXHbOT2l6qejA3Yee3KF2Hs/Vc1b0P2N9OuIuseaT+4eXud/YkzTfr0eeJu30hn+c7R6VQzyHH1hespHrmhqZxn+FfQkfqJ+OxwLU2zwKBQ7dRvLyLWdZd+Wi//E1mA2MuBny9LKnlgXASSUZjYDVIPjYPI0iAArtXoboqqqavhiEMptcFAKy17Mwpdop3oBC1yXlhN7EvsM/EDmVzI0yhFyeEripN1jzbthZzw8kFsYV2TTRs2xTSBY1Ob4j3odglpqh1efMN6mZoXOcKSMHbpksXVDDGxe8Epc20tGsBA9lL19pURGkGGs2H0K+ZCTiRR0W1px5BZDrzBbSOkLH4m+VELY3KBqjjhAFkGnhC9FV7GO/lKjubowPPmFIH7NKEPLfFneI3fZkBIBtbuN137HTN/KR+C/DZzCAGnlQOOdToFG7YW/AmmJHVdvwJ7VmmF3qR5QAWCIsanXgFGVjDDr2xr8/HSeE/nkLiux/psvdDcFZju3IbQKSja/0ywrK2bq1U3eUoRpTbzd7xycbTV8kRP+dRa1fR8o+kAkc0fHw5uR0fySiopiD2W1raUYbpynP8MXa8YUgBA1bN1uvbWnifXOQhcTFmTltMjevggVdAQ28Qx68rp7J8e15wqT7XnbiB1skc9s8YrtoneltUqP
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
      name: minio-secret
      namespace: minio
    type: Opaque
